apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkinsci/blueocean
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/var/jenkins_home"
              name: jenkins-data
            - mountPath: "/var/run/docker.sock"
              name: docker-daemon
      volumes:
        - name: jenkins-data
          emptyDir: {}
        - name: docker-daemon
          hostPath:
              path: "/var/run/docker.sock"